spring.application.name=personal-finance-tracker
server.port=3000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.url=jdbc:postgresql://localhost:5432/financial_traker
spring.datasource.username=josua
spring.datasource.password=josua
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
jwt.secret=yourSecretKey123
jwt.expiration=86400000